# Generated by Django 4.2.2 on 2023-08-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLoginDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(verbose_name='Student ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email address')),
                ('password', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
    ]
